### ISSUE TITLE
Description XML dans Type_course écrasée

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#10]
Les descriptions XML dans la table d'administration Type_Course sont écrasées lors d'une synchronisation Cloud. Etape pour reproduire le bug : 

* Administration, Type Course
* Ouvrir la description XML d'un type course (double clic sur l'icône) et la modifier. Par exemple, pour le type A en slalom : 
```
<?xml version="1.0" encoding="UTF-8"?>
<course>
	<phase code="Q" label="Qualification"
		<progression>FA</progression>
		<progression>FB</progression>
	</phase>

	<phase code="FA" label="Finale A">
	</phase>

	<phase code="FB" label="Finale B">
	</phase>
</course>
```
* Cliquer sur enregistrer
* Dans la table Type_Course, la ligne apparaît en rouge, cliquer sur Enregistrer
* La ligne repasse en vert
* Fermer la table
* Faire une synchro totale avec le cloud
* Administration, Type Course
* Ouvrir la description XML précédemment modifiée, celle-ci est maintenant vide.

**Comment by cosandco** [comment]
La synchronisation se fait toujours du Cloud vers le Local ...
si tu changes en local une table , à la prochaine synchro ces modifications seront écrasées ...
donc pour administrer les tables et les informations officielles il faut travailler sur la base "Cloud"

**Comment by niabb** [comment]
Effectivement j'avais oublié que le menu administration dépendait de la sélection locale/cloud.
