### ISSUE TITLE
Respect de l'ordre des épreuves

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#16]
Après importation d'une course en local, quand on ouvre la fenêtre "Dossard" ou "Programme des Epreuves", l'ordre des catégories n'est pas le même que celui défini dans la table "Programme Epreuve".

**Comment by cyrilc2** [comment]
idem en descente

**Comment by cosandco** [comment]
corrigé avec la version 2.0f ...
Effectivement c'est bien de s'appuyer sur les informations de la table Programme_Epreuve_Embarcation lors de l'initalisation
