### ISSUE TITLE
Erreur lors de la mise à jour des points

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#17]
Dans la liste des inscriptions, quand je fais outils / Mise à jour des points (sur une course slalom), j'ai pas mal d'erreurs. Mes bases sont pourtant bien à jour.
![image](https://user-images.githubusercontent.com/11386587/32877742-46afd69a-caa3-11e7-9aa3-2b26bf472f75.png)

**Comment by cosandco** [comment]
Corrigé avec la version 2.0f
L'internalisation avec en Français la virgule et pas le point était la cause du problème ...
