### ISSUE TITLE
[Descente] erreur mise à jour des Points

### ISSUE THREAD

**Issue by cyrilc2** [FFCK/compet-ffck#20]
impossible de mettre les points à jour pour une course descente sur la version 2.0d
![image](https://user-images.githubusercontent.com/33895732/33122249-fed0803a-cf76-11e7-8ef0-37d97fd457eb.png)

**Comment by cosandco** [comment]
corrigé avec la version 2.0f
L'internalisation avec en Français la virgule et pas le point était la cause du problème ...
