### ISSUE TITLE
[slalom] Retour à la ligne saisie manuelle des pénalités

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#22]
Lors de la saisie des pénalités manuelle, une fois la saisie sur la dernière porte effectuée, il serait plus pratique d'aller à la ligne à la première porte affichée, comme c'était le cas dans FFCanoe. Actuellement c'est la case suivante de la ligne (Inter) qui devient active.
![image](https://user-images.githubusercontent.com/11386587/33219994-b77525f8-d145-11e7-8c1b-e77e84b7a515.png)
Pour les courses où la saisie est manuelle, ça serait plus confort...

**Comment by cosandco** [comment]
Mise en place à partir de la version 2.0j
