### ISSUE TITLE
Crash dans la fenêtre de chrono

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#26]
Plusieurs clics répétés sur la flèche du bouton "Configuration" dans la fenêtre de chronométrage provoque un crash de CompetFFCK.
![image](https://user-images.githubusercontent.com/11386587/33221725-108bf9b2-d152-11e7-9283-e33dd6690e5c.png)
![image](https://user-images.githubusercontent.com/11386587/33221735-21efff3c-d152-11e7-9c0a-b28e00ec9de5.png)

**Comment by cosandco** [comment]
Menu et ToolBar dans la fenêtre des chronos ne présentent que les fonctionnalités validées
