### ISSUE TITLE
Erreur MySQL lors de l'enregistrement du temps

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#27]
Erreur lors de l'enregistrement d'un temps (après impulsion à l'arrivée), uniquement dans le cas de l'utilisation d'une base MySQL sous Linux : 
![image](https://user-images.githubusercontent.com/11386587/33229440-23e8e830-d1cf-11e7-98e6-9483697153ad.png)

**Comment by cosandco** [comment]
Resultat_Course et pas Resultat_course ...
Corrigé avec la version 2.0j
