### ISSUE TITLE
Mise en réseau impossible

### ISSUE THREAD

**Issue by niabb** [FFCK/compet-ffck#6]
Malgré la configuration en serveur avec les paramètres suivants, "Aucun réseau" reste affiché dans la barre inférieure, après validation de la fenêtre mais aussi après redémarrage du logiciel.
![image](https://cloud.githubusercontent.com/assets/11386587/22707907/96e14a0c-ed74-11e6-99bd-88d63b34cab9.png)

**Comment by cosandco** [comment]
Dans FFCANOE on pouvait gérer 0 à 1 réseau ...
Dans le competFFCK avec la notion de Connecteurs (Chrono et Display) on peut définir un nombre illimité de réseaux (TCP, UDP, ...)

**Comment by niabb** [comment]
C'est vrai que je ne me rappelais plus du fonctionnement de mise en réseau. Je teste ça ce soir. Par contre, si cette fenêtre de configuration réseau est inutile, ça serait bien de la retirer du menu Outils ?
